[server]
host: 0.0.0.0
port: 7125
max_upload_size: 1024 # (in MiB).  Default 1024 MiB
klippy_uds_address: ~/printer_data/comms/klippy.sock # Path to klippy Unix Domain Socket


[file_manager]
enable_object_processing: True

[authorization]
force_logins: False
trusted_clients:
  127.0.0.1
  ::1
  192.168.0.0/16
  2a00:6020:b2bb:a500::/64
  fd0e:c04f:17e1::/64
  fe80::/10
  192.168.0.0
  127.0.0.0/8
  FE80::/10
  ::1/128
cors_domains:
  http://voron.local
  https://voron.local
  *.local
  *.local:*
  *://localhost
  *://localhost:*
  *://my.mainsail.xyz

# enables partial support of Octoprint API
[octoprint_compat]

# enables moonraker to track and store print history.
[history]

# this enables moonraker announcements for mainsail
[announcements]
subscriptions:
    mainsail


[update_manager klipper]
report_anomalies: False
    
##################################################################################

# this enables moonraker's update manager
[update_manager]
refresh_interval: 168
enable_auto_refresh: True

[update_manager klipper-toolchanger-hard]
type: git_repo
path: ~/klipper-toolchanger
origin: https://github.com/contomo/klipper-toolchanger-hard.git
primary_branch: main
managed_services: klipper


[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: /home/contomo/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main



[update_manager axiscope]
type: git_repo
path: /home/klippy/axiscope
origin: https://github.com/nic335/Axiscope.git
primary_branch: main
is_system_service: True
managed_services: axiscope
